export const quoteData = [
    { text: `If you want to live a happy life, tie it to a goal, not to people or things.`, author: "Albert Einstein" },
    { text: `The purpose of our lives is to be happy.`, author: "Dalai Lama" },
    { text: `Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma – which is living with the results of other people’s thinking.`, author: "Steve Jobs" },
    { text: `Life is what happens when you’re busy making other plans.`, author: "John Lennon" },
    { text: `The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.`, author: "Henry Ford" },
    { text: `Get busy living or get busy dying.`, author: "Stephen King" },
    { text: `The big lesson in life, baby, is never be scared of anyone or anything.`, author: "Frank Sinatra" },
    { text: `You only live once, but if you do it right, once is enough.`, author: "Mae West" },
    { text: `Turn your wounds into wisdom.`, author: "Oprah Winfrey" },
    { text: ` Many of life’s failures are people who did not realize how close they were to success when they gave up.`, author: "Thomas A. Edison" },
    { text: `Live for each second without hesitation.`, author: "Elton John" },
    { text: `Life would be tragic if it weren’t funny.`, author: "Stephen Hawking" },
    { text: `The two most important days in your life are the day you are born and the day you find out why.`, author: "Mark Twain" },
    { text: `I believe every human has a finite number of heartbeats. I don’t intend to waste any of mine.`, author: "Neil Armstrong" },
    { text: `If you can do what you do best and be happy, you’re further along in life than most people.`, author: "Leonardo DiCaprio" },
    { text: `There are no regrets in life, just lessons.`, author: "Jennifer Aniston" },
    { text: `You must expect great things of yourself before you can do them.`, author: "Michael Jordan" },
  ];